title: TaneRS Blog
description: >
  To Record & Share
baseurl: "/"
theme: jekyll-theme-midnight

# tipue_search
tipue_search:
  include:
    pages: true
  exclude:
    files: [index.md, search.html, *_content.html]

# # paginate
# paginate: 10
# paginate_path: "/page:num/"