title: TaneRS Blog
description: >- # this means to ignore newlines until "baseurl:"
  To Record & Share
url: "https://tane-rs.github.io"
theme: jekyll-theme-midnight

tipue_search:
  include:
    pages: true
    collections: [apples, oranges]
