title: TaneRS Blog
description: >
  To Record & Share
baseurl: "/"
theme: jekyll-theme-midnight

plugins:
  - jekyll-paginate

paginate: 10
paginate_path: "/blog/page:num/"

# Search settings
tipue_search:
  include:
    pages: true
  exclude:
    files: [index.md, search.html]
