title: TaneRS Blog
description: >
  To Record & Share
baseurl: "/"
theme: jekyll-theme-midnight

# Search settings
tipue_search:
  include:
    pages: true
  exclude:
    files: [index.md, search.html]
