title: SHELDON IS ALWAYS LEARNING
description: >
    This site is moved to Gitbook => https://doc.sheldonl.dev
baseurl: "/"
theme: jekyll-theme-midnight

# tipue_search
tipue_search:
  include:
    pages: true
  exclude:
    files: [index.md, search.html, Blog_content.md, DS_AI_ML_content.md, CiscoCert_content.md]
