title: TaneRS Blog
description: >
  To Record & Share
baseurl: "/"

# Search settings
tipue_search:
  include:
    pages: true
  exclude:
    files: [index.md, search.html]

# Build settings
markdown: kramdown
theme: jekyll-theme-midnight
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
